//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobby
    {
        public int NumAl { get; set; }
        public int nSeq { get; set; }
        public string Descr { get; set; }
    
        public virtual Aluno Alunos { get; set; }
    }
}
